### ISSUE TITLE
How to Turn off headers?

### ISSUE THREAD

**Issue by gitgetgot** [19379/js-marc2003#10]
Hi,
is it possible, and how, to switch off those (a lot of space consuming) headers ?

![2](https://cloud.githubusercontent.com/assets/974980/13711392/98f1f0ba-e7be-11e5-8765-b426728ebbef.png)
![1](https://cloud.githubusercontent.com/assets/974980/13711393/9b9aa2a8-e7be-11e5-96d5-4528ce3b20b9.png)

**Comment by 19379** [comment]
Replace these existing functions in your panel

```javascript
function on_size() {
	panel.size();
	list.y = 0;
	list.w = panel.w - 20;
	list.h = panel.h;
	list.size();
}

function on_paint(gr) {
	panel.paint(gr);
	list.paint(gr);
}
```
