### ISSUE TITLE
Listenbrainz time elapsed

### ISSUE THREAD

**Issue by smoralis** [19379/js-marc2003#2]
this.time_elapsed++ is returning increment numbers 1,3,5  instead of 1,2,3

If this.target_time is an even number , track doesn't get submitted.

Reproduced on a clean install with jscript panel.

**Comment by 19379** [comment]
I cannot reproduce that here. Inserting `fb.trace(this.time_elapsed);` directly after `this.time_elapsed++;` shows this:

![lb](https://cloud.githubusercontent.com/assets/12451008/11775394/5af64cde-a236-11e5-94fa-43e7287900e0.png)
