### ISSUE TITLE
Guifx font failing to be recognized

### ISSUE THREAD

**Issue by Fironet** [19379/js-marc2003#5]
After installing Guifx in Windows it doesn't appear to be recognized by the script. The icons are latin characters rather than pictographs.

W8.1. Running fb2k in portable mode, if that makes a difference.

Example:

![Example](http://i.imgur.com/TQoNzwl.png)

Edit: Meant to be for the [JPlaylist-mod](https://github.com/19379/jsplaylist-mod).

**Comment by 19379** [comment]
If foobar was running when you installed the font then you need to restart.

Failing that, double check the font was installed properly by looking inside C:\Windows\Fonts

**Comment by Fironet** [comment]
Tried restarting fb2k initially, then restarted the system just in case. Still wasn't recognized.

Displays as being present in the installed Fonts, too.

![screen](http://i.imgur.com/dRNacx7.png)

**Comment by 19379** [comment]
I'm also using windows 8.1 and just tested foobar in portable mode and it works fine for me. What if you try and select `Guifx v2 Transports` in the default UI fonts section?? `File>Preferences>Display>Default UI>Colors and Fonts`
![font](https://cloud.githubusercontent.com/assets/12451008/12510497/31a37a92-c102-11e5-9b6f-1637c07acde5.png)

**Comment by Fironet** [comment]
Looks like this:

![screen](http://i.imgur.com/1eoxgic.png)

Wonder what it could be, since the leftmost Status column still displays the wrong characters.

**Comment by 19379** [comment]
Ah, it looks like you're missing the wingdings2/3 fonts.

[fonts.zip](https://github.com/19379/js-marc2003/files/100787/fonts.zip)

**Comment by Fironet** [comment]
> Ah, it looks like you're missing the wingdings2/3 fonts.

Isn't the GUIfx font meant to handle all the characters? Anyway, cheers. May need to update the instructions to mention the dependency.

**Comment by 19379** [comment]
It is the readme already but there isn't a link for the fonts. I'll update it.

**Comment by Fironet** [comment]
You're right, my bad. Worked as intended so closing the issue.

**Comment by 19379** [comment]
I've now updated the readme so all required fonts are in a single download.

**Comment by Fironet** [comment]
> I've now updated the readme so all required fonts are in a single download.

I'm sure this will help some like myself who missed it. Thanks.

If it's not too much to ask, would you happen to know what I'd need to edit to change the play/pause icon, selection 'tick' icon, and disable the play icon blinking when playing?

Those are about the only things that I've been looking to tweak since the fonts have displayed correctly.
