### ISSUE TITLE
Autoplaylist crashes. 

### ISSUE THREAD

**Issue by gitgetgot** [19379/js-marc2003#7]
Hi there, (and thankyou for continuing the great scripts for wsh panel & foobar2000 !!! )

I'm running on a german win7 64bit system w/ f2k 1.3.9, wsh panel mod 1.5.6

After downloading the [js_marc2003-v2.6.zip](https://github.com/19379/js-marc2003/releases/download/v2.6/js_marc2003-v2.6.zip), closing foobar2000, deleting the `wsh_settings` and `wsh_data` folders inside my foobar2000 folder, running foobar2000 and pasting the `js_marc2003\samples\autoplaylists.txt` into an existing (because I use autoplaylist since some years) WSH panel and overwritting the older script (from the now deleted `marc2003.x\samples8\autoplaylists.txt` folder), I got this error message:

```Scripting Engine Initialization Failed (Autoplaylists by marc2003, CODE: 0x80020101)
Check the console for more information (Always caused by unexcepted script error).```
```
[20:55:11] WSH Panel Mod (Autoplaylists by marc2003): Parsing file "E:\m\portable\foobar2000\js_marc2003\js\lodash.min.js"
[20:55:11] WSH Panel Mod (Autoplaylists by marc2003): Parsing file "E:\m\portable\foobar2000\js_marc2003\js\helpers.js"
[20:55:11] WSH Panel Mod (Autoplaylists by marc2003): Parsing file "E:\m\portable\foobar2000\js_marc2003\js\panel.js"
[20:55:11] WSH Panel Mod (Autoplaylists by marc2003): Parsing file "E:\m\portable\foobar2000\js_marc2003\js\list.js"
[20:55:11] Error: WSH Panel Mod (Autoplaylists by marc2003): Laufzeitfehler in Microsoft JScript:
Das Objekt unterstützt diese Eigenschaft oder Methode nicht.
File: E:\m\portable\foobar2000\js_marc2003\js\helpers.js
Ln: 45, Col: 1
<source text only available at compile time>
```
When I _experimentally_ go to Line 45 of `helpers` and delete those two lines
```
var tooltip = window.CreateTooltip(window.GetProperty("2K3.TOOLTIP.FONT.NAME", "Segoe UI"), window.GetProperty("2K3.TOOLTIP.FONT.SIZE", 12), window.GetProperty("2K3.TOOLTIP.FONT.STYLE", 0));
tooltip.SetMaxWidth(800);
```
autoplaylists does not crash at the start (I'm seeing an empty panel and can create a new autoplaylist) but after creating a new autoplaylist.
```
[21:12:20] Error: WSH Panel Mod (Autoplaylists by marc2003): Laufzeitfehler in Microsoft JScript:
Das Objekt unterstützt diese Eigenschaft oder Methode nicht.
File: E:\m\portable\foobar2000\js_marc2003\js\list.js
Ln: 871, Col: 6
<source text only available at compile time>
```

It seems, something is missing on my system:
> Das Objekt unterstützt diese Eigenschaft oder Methode nicht.

> Object Doesn't Support this Property or Method

I tried with foobar2000s portable_mode on and off.

I there anything I can tell you or do to help you helping me getting around that crash? ;-)

**Comment by 19379** [comment]
These scripts are for JScript Panel, not WSH panel mod. Look at the readme at the main github page and the wiki page which contains installation instructions.

https://github.com/19379/js-marc2003/wiki/Installation

JScript Panel is based on WSH panel mod but since I've made breaking changes that affect older WSH scripts, I made my own fork. You can run both components at the same time if you need to.

https://github.com/19379/foo-jscript-panel

**Comment by gitgetgot** [comment]
Thank you! That resolved all the troubles!
