### ISSUE TITLE
Q: Autoplaylist format changed. Any way to import the old autoplaylist-entries?

### ISSUE THREAD

**Issue by gitgetgot** [19379/js-marc2003#8]
Hi,
the format of the autoplaylists changed from something to json.
While it was very easy to edit (and quickly add a dozen new lines) those old `autoplaylist*` files with, say notepad++, it is now hard to do it without any good json software. (I don't know any json good editor, btw)

I have about 7 autoplaylists, each containing between 10 and 150 entries.
_(If you're asking yourself, wtf, who needs that much: I'm collecting song collections, means a million version of one song and for every song, I have generated an autoplaylist)_

Is there any known way to import the old autoplaylists to the new format?

**Comment by 19379** [comment]
This is a script with no UI that goes in a temporary panel. Just double click to run and the results should popup in a window. You can then copy/paste the results in to autoplaylists.json - I don't want the script to do that automatically as you can have full responsibility for not overwriting anything!!

```javascript
function on_mouse_lbtn_dblclk() {
	var filename = fb.ProfilePath + "wsh_settings\\autoplaylists.txt";
	var arr = utils.ReadTextFile(filename).split("\r\n");
	var data = [];
	for (var i = 0; i < arr.length; i++) {
		var temp = arr[i].split("¬");
		if (temp.length > 1) {
			data.push({
				name : temp[0],
				query : temp[1],
				sort : temp[2],
				forced : temp[3] == 6
			});
		}
	}
	if (data.length > 0)
		fb.ShowPopupMessage(JSON.stringify(data, null, "\t"));
}
```

**Comment by gitgetgot** [comment]
*Thank you* and sorry for the late reply, and forgive me not to know a lot about executing this script, but: Whats that for a programming language? 
Copying the script into a textfile, is easy, but what Extension to I give the textfile then? 
And what interpreter do I need to get it start and working?

**Comment by 19379** [comment]
The script itself goes in temporary panel and you double click to run it. I thought I made that clear the first time but I guess it needs repeating??

The contents of the popup window then need to be copy/pasted into a file named **autoplaylists.json** saved inside your **wsh_settings** folder. I thought you knew because you mentioned JSON in the first post.
