### ISSUE TITLE
LNTG: similar artists: on doubleclick: open f2k component instead of default browser

### ISSUE THREAD

**Issue by gitgetgot** [19379/js-marc2003#9]
Hi,
it would be a nice feature to have the component foo_quicksearch work on the selected similar artist.

That way, after doubleclicking any similar artists from the panel would open a new playlist with all the songs from that artist, which are in the users library.

Its a little bit what foo_softplaylists offers to its users. And its a very nice to have.

Is this possible?

**Comment by 19379** [comment]
You can modify the single click behaviour by replacing the existing **on_mouse_lbtn_up** function in your panel.

```javascript
function on_mouse_lbtn_up(x, y) {
	if (list.lastfm_mode == 0 && list.lastfm_artist_method == 0) {
		switch (true) {
		case !list.trace(x, y):
		case list.up_btn.lbtn_up(x, y):
		case list.down_btn.lbtn_up(x, y):
		case !list.in_range:
			break;
		case x > list.x + list.text_x && x < list.x + list.text_x + Math.min(list.data[list.index].width, list.text_width):
			var name = list.data[list.index].name;
			plman.CreateAutoPlaylist(plman.PlaylistCount, name, "artist IS " + name);
			plman.ActivePlaylist = plman.PlaylistCount - 1;
			break;
		}
	} else {
		list.lbtn_up(x, y);
	}
}
```

**Comment by gitgetgot** [comment]
Wow! :-)
That worked out of the box. 
That is very much appreciated!
With working code, it it much easier to experiment, than to write it from scratch while trying to fit the needs! Thank you again!
